version: '3.8' 

services:
  angular:
    build: ./Frontend  
    ports:
      - "4200:4200" 
    networks:
      - local

  web:
    build: ./Backend 
    ports:
      - "5000:5000"  
    depends_on:
      - db  
    networks:
      - local  

  db:
    image: postgres:latest 
    ports:
      - "5435:5435"  
    environment:
      POSTGRES_DB: usuarios 
      POSTGRES_USER: postgres   
      POSTGRES_PASSWORD: postgres 
    networks:
      - local  

networks:
  local: 

