version: '3.8'
services:
  client:
    build: ./Client
    ports:
      - "4200:4200" 
    networks:
      - local  # Nombre de la red personalizada

  server:
    build: ./Server
    ports:
      - "5000:5000"  
    depends_on:
      - db  
    networks:
      - local  # Nombre de la red personalizada

  db:
    image: postgres:16rc1-alpine 
    ports:
      - "5435:5435"  
    environment:
      POSTGRES_DB: usuarios 
      POSTGRES_USER: postgres   
      POSTGRES_PASSWORD: postgres 
    networks:
      - local  # Nombre de la red personalizada

networks:
  local:  # Definición de la red personalizada



    
